### ISSUE TITLE
Simplify craft commands

### ISSUE THREAD

**Issue by dria7226** [sikuli/craftml#1]
I was wondering: since the convention is to name the craftml file index.xml, could we simplify the preview and build commands to just be 'craft preview' and 'craft build' (and then it would just search for index.xml)

**Comment by calebhsu** [comment]
This would be problematic for multiple .xml files in the same directory though, especially if you name your files differently and want to preview them all.

**Comment by dria7226** [comment]
-when no .xml file is specified ***
