### ISSUE TITLE
Bug in transform scale, translate, & rotate syntax

### ISSUE THREAD

**Issue by calebhsu** [sikuli/craftml#10]
Editor will break if there are spaces in scale, translate, and rotate, as shown below:

![example](https://cloud.githubusercontent.com/assets/9546162/7738901/f6423d92-ff16-11e4-8e00-50831d4d0a0d.png)
![bug](https://cloud.githubusercontent.com/assets/9546162/7965648/1818e40a-09dc-11e5-94c2-552e8fe033bd.png)

**Comment by doubleshow** [comment]
this issue has been fixed.
