### ISSUE TITLE
tighten() can't be used in line

### ISSUE THREAD

**Issue by calebhsu** [sikuli/craftml#13]
Syntax error when tighten() is used in line:
![error](https://cloud.githubusercontent.com/assets/9546162/8117851/a7d69246-1048-11e5-96ac-f499c641fd0b.png)

Not an issue when used this way:
![bug](https://cloud.githubusercontent.com/assets/9546162/8117874/d7781376-1048-11e5-9000-ff890192c057.png)

**Comment by doubleshow** [comment]
This issue has been fixed.
